language: python

python:
  - 3.6.7

install:
  - pip install -r requirements.txt

  - pip install coveralls

env:
  - FLASK_VERSION=1.0.2

script:
  - pytest --cov-report --cov=app/api
  - coveralls

after_success:
  - coveralls